
# This script takes a snapshot of all of the source code files
# that are autogenerated by the reposit SWIG module.

import os
import sys
import glob
import shutil

SUB_DIRS = (
    'QuantLibAddin2/qlo',
    'QuantLibAddin2/qlo/valueobjects',
    'QuantLibAddin2/qlo/serialization/create',
    'QuantLibAddin2/qlo/serialization/register',
    'QuantLibAddin2/AddinCpp',
    'QuantLibXL2/qlxl/functions',
    'QuantLibXL2/qlxl/register'
)

OUT_ROOT_DIR = './diffout'

def deriveDir():
    i = 0;
    d = OUT_ROOT_DIR + "/d" + str(i)
    while os.path.exists(d):
        i += 1
        d = OUT_ROOT_DIR + "/d" + str(i)
    return d

cwd = os.getcwd()
rootDir = cwd[:-17] # strip off rightmost 17 characters for "reposit/dev_tools"

if not os.path.exists(OUT_ROOT_DIR):
    os.mkdir(OUT_ROOT_DIR)

outDir = deriveDir()
os.mkdir(outDir)

for subDir in SUB_DIRS:
    sourceDir = rootDir + '/' + subDir
    targetDir = outDir + '/' + subDir
    os.makedirs(targetDir)
    for f in glob.glob(sourceDir + '/*.?pp'):
        fileName = os.path.basename(f)
        print 'processing file ' + subDir + '/' + fileName
        shutil.copy(f, targetDir + '/' + fileName)

print 'output directory is ' + outDir
if sys.platform == 'win32':
    raw_input('press any key to exit')

